-- Recovery only: restores original client permissions and policies.
-- This reintroduces the original exposure; prefer fixing the backend if necessary.
BEGIN;
DROP POLICY IF EXISTS "Block direct client access" ON public."extras";
REVOKE ALL PRIVILEGES ON TABLE public."extras" FROM PUBLIC, anon, authenticated;
GRANT INSERT ON TABLE public."extras" TO "anon";
GRANT SELECT ON TABLE public."extras" TO "anon";
GRANT UPDATE ON TABLE public."extras" TO "anon";
GRANT DELETE ON TABLE public."extras" TO "anon";
GRANT TRUNCATE ON TABLE public."extras" TO "anon";
GRANT REFERENCES ON TABLE public."extras" TO "anon";
GRANT TRIGGER ON TABLE public."extras" TO "anon";
GRANT INSERT ON TABLE public."extras" TO "authenticated";
GRANT SELECT ON TABLE public."extras" TO "authenticated";
GRANT UPDATE ON TABLE public."extras" TO "authenticated";
GRANT DELETE ON TABLE public."extras" TO "authenticated";
GRANT TRUNCATE ON TABLE public."extras" TO "authenticated";
GRANT REFERENCES ON TABLE public."extras" TO "authenticated";
GRANT TRIGGER ON TABLE public."extras" TO "authenticated";
CREATE POLICY "All users can create in extras" ON public."extras" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (true);
CREATE POLICY "All users can delete from extras" ON public."extras" AS PERMISSIVE FOR DELETE TO "authenticated" USING (true);
CREATE POLICY "All users can read from extras" ON public."extras" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "All users can update in extras" ON public."extras" AS PERMISSIVE FOR UPDATE TO "authenticated" WITH CHECK (true);
DROP POLICY IF EXISTS "Block direct client access" ON public."fisicos";
REVOKE ALL PRIVILEGES ON TABLE public."fisicos" FROM PUBLIC, anon, authenticated;
GRANT INSERT ON TABLE public."fisicos" TO "anon";
GRANT SELECT ON TABLE public."fisicos" TO "anon";
GRANT UPDATE ON TABLE public."fisicos" TO "anon";
GRANT DELETE ON TABLE public."fisicos" TO "anon";
GRANT TRUNCATE ON TABLE public."fisicos" TO "anon";
GRANT REFERENCES ON TABLE public."fisicos" TO "anon";
GRANT TRIGGER ON TABLE public."fisicos" TO "anon";
GRANT INSERT ON TABLE public."fisicos" TO "authenticated";
GRANT SELECT ON TABLE public."fisicos" TO "authenticated";
GRANT UPDATE ON TABLE public."fisicos" TO "authenticated";
GRANT DELETE ON TABLE public."fisicos" TO "authenticated";
GRANT TRUNCATE ON TABLE public."fisicos" TO "authenticated";
GRANT REFERENCES ON TABLE public."fisicos" TO "authenticated";
GRANT TRIGGER ON TABLE public."fisicos" TO "authenticated";
CREATE POLICY "All users can create in fisicos" ON public."fisicos" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (true);
CREATE POLICY "All users can delete from fisicos" ON public."fisicos" AS PERMISSIVE FOR DELETE TO "authenticated" USING (true);
CREATE POLICY "All users can read from fisicos" ON public."fisicos" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "All users can update in fisicos" ON public."fisicos" AS PERMISSIVE FOR UPDATE TO "authenticated" WITH CHECK (true);
DROP POLICY IF EXISTS "Block direct client access" ON public."suspensos";
REVOKE ALL PRIVILEGES ON TABLE public."suspensos" FROM PUBLIC, anon, authenticated;
GRANT INSERT ON TABLE public."suspensos" TO "anon";
GRANT SELECT ON TABLE public."suspensos" TO "anon";
GRANT UPDATE ON TABLE public."suspensos" TO "anon";
GRANT DELETE ON TABLE public."suspensos" TO "anon";
GRANT TRUNCATE ON TABLE public."suspensos" TO "anon";
GRANT REFERENCES ON TABLE public."suspensos" TO "anon";
GRANT TRIGGER ON TABLE public."suspensos" TO "anon";
GRANT INSERT ON TABLE public."suspensos" TO "authenticated";
GRANT SELECT ON TABLE public."suspensos" TO "authenticated";
GRANT UPDATE ON TABLE public."suspensos" TO "authenticated";
GRANT DELETE ON TABLE public."suspensos" TO "authenticated";
GRANT TRUNCATE ON TABLE public."suspensos" TO "authenticated";
GRANT REFERENCES ON TABLE public."suspensos" TO "authenticated";
GRANT TRIGGER ON TABLE public."suspensos" TO "authenticated";
CREATE POLICY "All users can create in suspensos" ON public."suspensos" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (true);
CREATE POLICY "All users can delete from suspensos" ON public."suspensos" AS PERMISSIVE FOR DELETE TO "authenticated" USING (true);
CREATE POLICY "All users can read from suspensos" ON public."suspensos" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "All users can update in suspensos" ON public."suspensos" AS PERMISSIVE FOR UPDATE TO "authenticated" WITH CHECK (true);
DROP POLICY IF EXISTS "Block direct client access" ON public."users";
REVOKE ALL PRIVILEGES ON TABLE public."users" FROM PUBLIC, anon, authenticated;
GRANT INSERT ON TABLE public."users" TO "anon";
GRANT SELECT ON TABLE public."users" TO "anon";
GRANT UPDATE ON TABLE public."users" TO "anon";
GRANT DELETE ON TABLE public."users" TO "anon";
GRANT TRUNCATE ON TABLE public."users" TO "anon";
GRANT REFERENCES ON TABLE public."users" TO "anon";
GRANT TRIGGER ON TABLE public."users" TO "anon";
GRANT INSERT ON TABLE public."users" TO "authenticated";
GRANT SELECT ON TABLE public."users" TO "authenticated";
GRANT UPDATE ON TABLE public."users" TO "authenticated";
GRANT DELETE ON TABLE public."users" TO "authenticated";
GRANT TRUNCATE ON TABLE public."users" TO "authenticated";
GRANT REFERENCES ON TABLE public."users" TO "authenticated";
GRANT TRIGGER ON TABLE public."users" TO "authenticated";
CREATE POLICY "Admins can manage users" ON public."users" AS PERMISSIVE FOR ALL TO "authenticated" USING (((auth.jwt() ->> 'role'::text) = 'admin'::text));
CREATE POLICY "All users can create users" ON public."users" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (true);
CREATE POLICY "All users can delete users" ON public."users" AS PERMISSIVE FOR DELETE TO "authenticated" USING (true);
CREATE POLICY "All users can read users" ON public."users" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "All users can update users" ON public."users" AS PERMISSIVE FOR UPDATE TO "authenticated" WITH CHECK (true);
COMMIT;
